### ISSUE TITLE
Local module: bed_filter

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/genomenote#3]
### Description of feature

Software tool: `sort, paste, sed, awk, tr, sort`

Function: Filter the bed file

Current commands:
```
$$self{bamToBed} | sort -k4 --parallel=8 -S50G > $outfile.part])

cmd(qq[paste -d '\\t' - - < $bed | sed 's/-/_/g' | awk 'BEGIN {FS="\\t"; OFS="\\t"} {if (\$1 > \$7) {print substr(\$4,1,length(\$4)-2),\$12,\$7,\$8,"16",\$6,\$1,\$2,"8",\$11,\$5} else { print substr(\$4,1,length(\$4)-2),\$6,\$1,\$2,"8",\$12,\$7,\$8,"16",\$5,\$11} }' | tr '\\-+' '01'  | sort --parallel=8 -S10G -k3,3d -k7,7d > $outfile.part])
```

**Comment by priyanka-surana** [comment]
Current plan is to write a bash script that accepts the BED file from `bamtobed` and does the processing and exits the filtered BED file.

**Comment by priyanka-surana** [comment]
@muffato Can we simplify the commands, especially the print sections? I would like to reduce the number of pipes, or I can just break it. Also the `sort` commands have a `parallel` and `buffer` tag which needs to be dynamic.

**Comment by muffato** [comment]
Summary of the discussion yesterday:
1. Check (e.g. with Shane or Yumi) whether the `bamtobed` can be sorted with `bedtools sort` as in the [existing nf-core module](https://github.com/nf-core/modules/blob/master/modules/bedtools/bamtobed/main.nf#L28). \[I think it's unlikely to be the case because `bedtools sort` sorts by position, whereas we need to sort by the 4th column, which is likely a feature name, so that the `paste` command, which concatenates consecutive lines, can pair reads or something\]. Fall back to making a local copy of the bamtobed module that uses the regular sort as in https://github.com/sanger-tol/genomenote/issues/3#issue-1221070475 but using the Nextflow task's memory/cpu settings.
2. `awk` is the most straightforward way of rearranging the column, so keep on using that (+ `paste`, etc) *and* the sort (again, making it use Nextflow task's memory/cpu settings).

**Comment by priyanka-surana** [comment]
@muffato Updated commands

`sort`
```
conda (params.enable_conda ? "conda-forge::sed=4.7" : null)
container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
       'https://depot.galaxyproject.org/singularity/ubuntu:20.04' :
       'ubuntu:20.04' }"
...
sort $args --parallel=$cpus -S${buffer} $bed > $outfile
```

everything else
```
conda (params.enable_conda ? "conda-forge::gawk=5.1.0" : null)
container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
       'https://depot.galaxyproject.org/singularity/gawk:5.1.0' :
       'quay.io/biocontainers/gawk:5.1.0' }"
...
paste -d '\t' - - < $infile | sed 's/-/_/g' | awk 'BEGIN {FS="\t"; OFS="\t"} {if ($1 > $7) {print substr($4,1,length($4)-2),$12,$7,$8,"16",$6,$1,$2,"8",$11,$5} else { print substr($4,1,length($4)-2),$6,$1,$2,"8",$12,$7,$8,"16",$5,$11} }' | tr '_+' '01' > $outfile
...
```
